#!/usr/bin/env bash 

scenes=()
scenes+=("BREAK")
while read -r line; do
	scenes+=("$line")
done < <(ls test_scenes/)
PS3="Scene #: "
select scene in "${scenes[@]}";  do
	if [ "$scene" = "BREAK" ]; then
		break
	fi
	echo "Rendering: $scene"
	./RT test_scenes/"$scene"
done
